/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.conditions;

import automata.modular.ConditionWrapper;
import automata.modular.ModularAutomata;
import automata.modular.conditions.ConditionAnd;
import gui.ConditionFrame;
import javax.swing.JFrame;


public class AndPanel extends javax.swing.JPanel {

    /**
     * Creates new form LessThanPanel
     */
    private ModularAutomata automata;
    private ConditionAnd andCondition;
    public AndPanel() {
	initComponents();
	
	
    }
    
    private JFrame parent;
    public void setAutomataAndCondition(ModularAutomata automata, ConditionAnd andCondition, JFrame parent) {
	this.automata = automata;
	this.andCondition = andCondition;
	
	this.parent = parent;
	
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        setLeftConditionButton = new javax.swing.JButton();
        setRightConditionButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        leftTextField = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        rightTextField = new javax.swing.JTextArea();

        jLabel2.setText("AND");

        setLeftConditionButton.setText("Set Condition 1");
        setLeftConditionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLeftConditionButtonActionPerformed(evt);
            }
        });

        setRightConditionButton.setText("Set Condition 2");
        setRightConditionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setRightConditionButtonActionPerformed(evt);
            }
        });

        leftTextField.setColumns(20);
        leftTextField.setRows(5);
        jScrollPane1.setViewportView(leftTextField);

        rightTextField.setColumns(20);
        rightTextField.setRows(5);
        jScrollPane2.setViewportView(rightTextField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(setLeftConditionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)
                        .addGap(78, 78, 78)
                        .addComponent(setRightConditionButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(setLeftConditionButton)
                    .addComponent(setRightConditionButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setLeftConditionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLeftConditionButtonActionPerformed
        ConditionWrapper conditionWrapper = new ConditionWrapper(andCondition.getConditionLeft());
	
	new ConditionFrame(parent, automata, conditionWrapper).addWindowListener(new java.awt.event.WindowAdapter() {
	@Override
	    public void windowClosing(java.awt.event.WindowEvent windowEvent) {
		andCondition.setConditionLeft(conditionWrapper.condition);
		leftTextField.setText(conditionWrapper.condition.toString());
	    }
	});
    }//GEN-LAST:event_setLeftConditionButtonActionPerformed

    private void setRightConditionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setRightConditionButtonActionPerformed
        ConditionWrapper conditionWrapper = new ConditionWrapper(andCondition.getConditionRight());
	
	new ConditionFrame(parent, automata, conditionWrapper).addWindowListener(new java.awt.event.WindowAdapter() {
	@Override
	    public void windowClosing(java.awt.event.WindowEvent windowEvent) {
		andCondition.setConditionRight(conditionWrapper.condition);
		rightTextField.setText(conditionWrapper.condition.toString());
	    }
	});
    }//GEN-LAST:event_setRightConditionButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea leftTextField;
    private javax.swing.JTextArea rightTextField;
    private javax.swing.JButton setLeftConditionButton;
    private javax.swing.JButton setRightConditionButton;
    // End of variables declaration//GEN-END:variables
}
